# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Engine_config = debug
  Editor_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Engine_config = release
  Editor_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  Engine_config = dist
  Editor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Engine Editor

.PHONY: all clean help $(PROJECTS) Dependencies TextureGenerator

all: $(PROJECTS)

Dependencies: GLFW

TextureGenerator: Editor Engine

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Vendor/Library/GLFW -f Makefile config=$(GLFW_config)
endif

Engine: GLFW
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

Editor: Engine
ifneq (,$(Editor_config))
	@echo "==== Building Editor ($(Editor_config)) ===="
	@${MAKE} --no-print-directory -C Editor -f Makefile config=$(Editor_config)
endif

clean:
	@${MAKE} --no-print-directory -C Vendor/Library/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C Editor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Engine"
	@echo "   Editor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"